### ISSUE TITLE
Feature: Support comparing result of 2 different machine with only one dimension and other are ignore

### ISSUE THREAD

**Issue by NgSherly** [intel/lkp-tests#153]
Please help to evaluate and consider to enhance the lkp ncompare feature by enabling of comparing result of 2 different machine with only one dimension  and other are ignored. 

For example:
**Machine A:** 
Hostname: flexbj-riscv
Commit: 5.19.0
Compiler: gcc-11
OS: Ubuntu

**MachineB:**
Hostname: flexbj-x86
Commit: 5.13.0-41-generic
Compiler: gcc-9
Os: Ubuntu

Example output of comparing based on hostname:
tbox_group: bs/buffered/commit/compiler/direct/disk/ioengine/kconfig/rootfs/rw/test_size/testcase
  flexbj-x86: 4K/0/5.13.0-41-generic/gcc-9/1/1SSD/sync/defconfig/ubuntu/randread/1g/fio-simple
  flexbj-riscv:4K/0/5.19.0/gcc-11/1/1SSD/sync/defconfig/ubuntu/randread/1g/fio-simple

flexbj-x86               flexbj-riscv 
---------------- --------------------------- 
       fail:runs  %reproduction    fail:runs
           |             |             |    
          1:1         -100%            :1     dmesg.Mem-Info
          1:1         -100%            :1     dmesg.RIP:reserve_ds_buffers
          1:1         -100%            :1     dmesg.WARNING:at_arch/x86/events/intel/ds.c:#reserve_ds_buffers
          1:1         -100%            :1     dmesg.boot_failures

**Comment by xilabao** [comment]
Hi @NgSherly , we have supported this feature, could you give it a try? the example is in the changelog of commit 71e95bbec8aaa0727d7a1f103c528b6329b0b39f

**Comment by NgSherly** [comment]
if with the command of **"lkp ncompare -c tbox_group -j /lkp/result/stream/10000000-100%-true/flexbj-riscv3/ -j /lkp/result/stream/10000000-100%-true/flexbj-up2 -a**" , i can get the result comparison output as below:
   flexbj-riscv3                  flexbj-up2 
---------------- --------------------------- 
       fail:runs  %reproduction    fail:runs
           |             |             |    
       7530:1     65107060%      658601:1     dmesg.timestamp:last
           :1          100%           1:1     kmsg.EDAC_pnd2:Failed_to_register_device_with_error
           :1          100%           1:1     kmsg.mtd_device_must_be_supplied(device_name_is_empty)
           :1          100%           1:1     kmsg.pktgen:no_such_netdevice:~eth#~
           :1          100%           1:1     kmsg.segfault_at_ip_sp_error
           :1          475%           4:1     kmsg.timestamp:EDAC_pnd2:Failed_to_register_device_with_error
       7530:1     65107060%      658601:1     kmsg.timestamp:last
           :1          331%           3:1     kmsg.timestamp:mtd_device_must_be_supplied(device_name_is_empty)
         %stddev     %change         %stddev
             \          |                \  
      1240          +588.0%       8532        stream.add_bandwidth_MBps
  10000000            +0.0%   10000000        stream.array_size
      1232          +557.3%       8101        stream.copy_bandwidth_MBps
      8.00            +0.0%       8.00        stream.element_size_byte
      1106          +652.7%       8331        stream.scale_bandwidth_MBps

**Observation 1:**
it doesn't print out the output of the commit/compiler/lconfig/nr_task...etc as below for each of the host:
  commit/compiler/kconfig/nr_task/rootfs/runtime/test/testcase:
    5.15.0-43-generic/gcc-11/defconfig/1/ubuntu/300s/whetstone-double/unixbench
Could you please add those information?


**Observation 2:**
it seem like need to have the fix path for it to work. If i'm using the command to specific the hostname/testcase, it will not have any output. For example:
**lkp ncompare -c tbox_group -s tbox_group=flexbj-riscv3/testcase=stream -o tbox_group=flexbj-up2 -a**
Could we compare the result by specific the hostname/testcase in the command?

**Comment by xilabao** [comment]
Hi @NgSherly, we have updated the code to support them, please refer to the changelog in https://github.com/intel/lkp-tests/commit/8174f49f5741f22487b2b9ddde0e0f14092c9cdf

**Comment by NgSherly** [comment]
hi @xilabao , i still not able to get the output with this latest changes.
Both of the command below also doesn't work.

lkp ncompare -s testcase=stream/commit="5.19.0-00005-gf4d0609f50ba" -o commit="5.15.0-43-generic" -a
lkp ncompare -s testcase=stream/commit="5.19.0-00005-gf4d0609f50ba"/tbox_group=flexbj-riscv3 -o commit="5.15.0-43-generic"/tbox_group=flexbj-up2

**Comment by xilabao** [comment]
@NgSherly can you share the two result_root paths? e.g. /result/netperf/cs-localhost-performance-ipv4-16-300s-TCP_CRR-ucode=0x7002501/lkp-cpl-4sp1/debian-11.1-x86_64-20220510.cgz/x86_64-rhel-8.3/gcc-11/7ce2aa6d7fe121e243e1c8a8093911fecdf1c88e

**Comment by NgSherly** [comment]
Here is the resutl root path:
/lkp/result/stream/10000000-100%-true/flexbj-riscv3/ubuntu/defconfig//etc/alternatives/gcc/5.19.0-00005-gf4d0609f50ba
/lkp/result/stream/10000000-100%-true/flexbj-up2/ubuntu/defconfig/gcc-11/5.15.0-43-generic

**Comment by xilabao** [comment]
> /lkp/result/stream/10000000-100%-true/flexbj-riscv3/ubuntu/defconfig//etc/alternatives/gcc/5.19.0-00005-gf4d0609f50ba
the path looks wrong, '/etc/alternatives' is a typo?

can you try the below command?
`lkp ncompare -s testcase=stream/commit="5.19.0-00005-gf4d0609f50ba"/tbox_group=flexbj-riscv3/compiler=gcc -o commit="5.15.0-43-generic"/tbox_group=flexbj-up2/compiler=gcc-11 -a`

**Comment by NgSherly** [comment]
> > /lkp/result/stream/10000000-100%-true/flexbj-riscv3/ubuntu/defconfig//etc/alternatives/gcc/5.19.0-00005-gf4d0609f50ba
> > the path looks wrong, '/etc/alternatives' is a typo?
> 
> can you try the below command? `lkp ncompare -s testcase=stream/commit="5.19.0-00005-gf4d0609f50ba"/tbox_group=flexbj-riscv3/compiler=gcc -o commit="5.15.0-43-generic"/tbox_group=flexbj-up2/compiler=gcc-11 -a`

still no output

**Comment by xilabao** [comment]
can you run `lkp merge` for the path again? "/etc/alternatives" shouldn't exist.
/lkp/result/stream/10000000-100%-true/flexbj-riscv3/ubuntu/defconfig//etc/alternatives/gcc/5.19.0-00005-gf4d0609f50ba

and is there any output if using `lkp ncompare -j path1 -j path2` -a?

**Comment by NgSherly** [comment]
> can you run `lkp merge` for the path again? "/etc/alternatives" shouldn't exist. /lkp/result/stream/10000000-100%-true/flexbj-riscv3/ubuntu/defconfig//etc/alternatives/gcc/5.19.0-00005-gf4d0609f50ba
> 
> and is there any output if using `lkp ncompare -j path1 -j path2` -a?

i have the "/etc/alternatives/gcc" path for the compiler.
"lkp ncompare -c tbox_group -j /lkp/result/stream/10000000-100%-true/flexbj-riscv3/ -j /lkp/result/stream/10000000-100%-true/flexbj-up2 -a " is working fine.

**Comment by xilabao** [comment]
> i have the "/etc/alternatives/gcc" path for the compiler.

okay, I see,  the path can't be parsed by `lkp ncompare`, the items in "testcase=stream/commit="5.19.0-00005-gf4d0609f50ba"/tbox_group=flexbj-riscv3" are divided by '/', you can change the compiler name in job.yaml and run `lkp merge`, than lkp ncompare can compare with the new name.

**Comment by NgSherly** [comment]
i tried to edit compiler name in the job file and run lkp merge. 
Weird that i need to put testcase, commit and tbox_group in order to get the output, else, there is no output.
![image](https://user-images.githubusercontent.com/62603756/188088154-41aa2e47-1f79-4788-bd27-2848b1659411.png)

**Comment by xilabao** [comment]
yes, it's expected, only when there are more than one item in "-o" option, it can be compared, otherwise, `lkp ncompare` will keep the strict limit to only compare the target item.

**Comment by NgSherly** [comment]
Got it. Noted and thanks! :)

**Comment by NgSherly** [comment]
![image](https://user-images.githubusercontent.com/62603756/189903881-360f7cca-379c-458c-b645-fa7d2926b6e7.png)
seem like it can display all the test belong to the same testcase probably on same page.

it only can display single test by fixing the "test" in the command:
![image](https://user-images.githubusercontent.com/62603756/189904445-6b622b5f-cf3f-4078-8441-fa3744ad5168.png)

**Comment by xilabao** [comment]
Yes,  option --search/-s is to find all paths that match the rules.
